language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install codecov
  - pip install -r requirements.txt
script:
  - coverage run test_simple_pyyuque.py
after_success:
  - codecov
notifications:
  email:
    recipients:
      - zhangjian12424@gmail.com
    on_success: always
    on_failure: always